src/html_tag.cpp

Made this change because I was having trouble using vertical-align : bottom inside table <td> elements.

fixed positioning when using height percentages.

---

src/borders.h
src/media_query.cpp
src/style.cpp
src/types.h

Simple coding errors detected, and corrected.

missing or incorrect code

---

include/litehtml.h

delete repeated include of "litehtml/stylesheet.h" and "litehtml/html_tag.h"

delete repeated include

---

README.md
containers/haiku/container_haiku.cpp
containers/haiku/container_haiku.h

Haiku - Added HTML string rendering support. Added Haiku litebrowser links (hope this is ok!)

Feature haiku

---

src/html_tag.cpp

This fixes #136 and also makes sure that #51 remains fixed.

Fix #136 without breaking #51

---

src/html_tag.cpp

Amends 58e92d6dc649c4be469fad4912cc4ce25c6f11a5

Fix box width for ordered list markers

---

include/litehtml/html.h
include/litehtml/os_types.h
src/html.cpp

Reverts litehtml/litehtml#177
Idea is good, bu this pull request breaks everything :(

Revert "Add a custom 'strtod' implementation that ignores the current locale."

---

src/el_before_after.cpp

Fix nonstandard behavior of :before :after

---

include/master.css
src/element.cpp
src/html_tag.cpp
src/table.cpp

Fix table issues

---

containers/gdiplus/gdiplus_container.cpp
containers/win32/win32_container.cpp

Solve the bug when the program is closed

Solve the problem that the parent class calls the subclass function in the destructor

---

containers/linux/cairo_borders.cpp
containers/linux/cairo_borders.h
containers/linux/container_linux.cpp
include/litehtml/web_color.h

Added support for styles:
dotted, dashed, double, inset, outset, groove, ridge

Linux container: added support for borders style

---

CMakeLists.txt
containers/test/Bitmap.cpp
doc/document_createFromString.txt
include/litehtml/html.h
include/litehtml/types.h
src/document_container.cpp
src/encodings.cpp
src/html.cpp
src/style.cpp
src/utf8_strings.cpp
test/encodings_test.cpp

Implement "prescan the byte stream to determine its encoding"

---

include/litehtml/html.h
include/litehtml/table.h
include/litehtml/types.h
src/css_parser.cpp
src/css_selector.cpp
src/css_tokenizer.cpp
src/encodings.cpp
src/html_microsyntaxes.cpp
src/media_query.cpp
src/string_id.cpp
src/style.cpp

- replace deprecated c-style headers
- including iso646.h has no effect in C++
- use bool instead of int
- replace typedefs with "using"

Modernize some code based on static analysis

---

include/litehtml/html.h
src/stylesheet.cpp

- remove const on bool parameter
- replace problematic character encodings in comments in stylesheet.cpp

Two small fixes

---

src/css_tokenizer.cpp
src/el_before_after.cpp
src/el_text.cpp
src/url.cpp

https://releases.llvm.org/17.0.1/tools/clang/tools/extra/docs/clang-tidy/checks/modernize/return-braced-init-list.html
Part of #336

{style} Prefer brace list returns

---

include/litehtml/borders.h
include/litehtml/css_margins.h
include/litehtml/css_offsets.h
include/litehtml/types.h
src/line_box.cpp

https://releases.llvm.org/17.0.1/tools/clang/tools/extra/docs/clang-tidy/checks/modernize/use-equals-default.html
Part of #336

{style} Use "= default" where possible

---

src/encodings.cpp

https://releases.llvm.org/17.0.1/tools/clang/tools/extra/docs/clang-tidy/checks/modernize/loop-convert.html
Part of #336

{style} Prefer range-based loops

---

CMakeLists.txt
containers/cairo/container_cairo_pango.cpp
include/litehtml/css_properties.h
include/litehtml/el_style.h
include/litehtml/html.h
include/litehtml/line_box.h
include/litehtml/types.h
src/css_properties.cpp
src/el_style.cpp
src/el_text.cpp
src/html_tag.cpp
src/line_box.cpp
src/render_block.cpp
src/render_image.cpp
src/render_inline_context.cpp

Changes:
* Added subscripts/superscripts baseline shift to the font_metrics
* Improved rendering of inline elements with top and bottom vertical align
* Improved rendering of the line-height property

Updated inline layout rendering

---

containers/cairo/container_cairo.cpp
include/litehtml/css_properties.h

Returning string by value causes read-after-free error.

Fixed memory leaks and possible crashes

---

support/README.md
support/gtkmm4/html_widget.cpp
support/gtkmm4/html_widget.h
support/webpage/draw_buffer.cpp
support/webpage/draw_buffer.h
support/webpage/html_host.h
support/webpage/http_request.cpp
support/webpage/http_request.h
support/webpage/http_requests_pool.cpp
support/webpage/http_requests_pool.h
support/webpage/web_history.cpp
support/webpage/web_history.h
support/webpage/web_page.cpp
support/webpage/web_page.h

Includes:
* GTKMM4 Widget
* Cairo Surface based draw buffer
* Multi-threaded web_page class based on container_cairo_pango

Add litehtml support sources

---

src/css_parser.cpp

fix #397
call `remove_whitespace` base on `css_token_vector` size.

Optimizing remove_whitespace performance

---

.clang-format
.gitignore
include/litehtml/css_properties.h
include/litehtml/font_description.h
include/litehtml/string_id.h
include/litehtml/style.h
include/litehtml/types.h
src/css_properties.cpp
src/style.cpp

Supported these css properties:
- `text-emphasis`
- `text-emphasis-color`
- `text-emphasis-position`

Support 'text-emphasis' css properties.

---

.clang-format
containers/cairo/container_cairo.cpp
containers/cairo/render2png.cpp
include/litehtml/document_container.h
src/document.cpp
src/render_item.cpp
support/gtkmm4/html_widget.cpp
support/gtkmm4/html_widget.h
support/webpage/draw_buffer.cpp
support/webpage/html_host.h
support/webpage/web_page.cpp
support/webpage/web_page.h

* ```document_container::get_client_rect``` was renamed to ```get_viewport```.
* updated ```draw_buffer``` support class to handle fixed elements on scroll

fixed: elements with 'position:fixed' have issue with draw

---

doc/document_container.md
doc/document_createFromString.md
doc/using.md

Documentation is added to the source tree and updated to the latest litehtml changes.

Added documentation

---

CMakeLists.txt
include/litehtml/html_tag.h
src/html_tag.cpp
src/line_box.cpp

fix: incorrect baseline calculation and list markers position
