litehtml/litehtml

containers/cairo/cairo_container.cpp
containers/cairo/cairo_container.h
containers/linux/container_linux.cpp
containers/linux/container_linux.h
src/document.cpp
src/document.h
src/html.h
src/html_tag.cpp
src/types.h

This PR implements support for :lang(en-US) pseudo selector.
Containers need to implement get_language(), setting both lang and culture.

Support for lang selector

---

src/html_tag.cpp

When a pseudo selector was used in parent selection, the :after/:before would not be processed correctly

Fixed the following css selector: .foo:nth-child(1) .bar:after/before

---

src/box.cpp

relative top and bottom are expressed in parent space, using an offset relative to parent dimensions

Fix relative top and bottom offset when using percentages

---

src/css_selector.cpp
src/css_selector.h
src/element.cpp
src/element.h
src/html_tag.cpp
src/html_tag.h

Animating document is usually done by add and removing classes. 
This PR add a set_class that allows to add and remove classes dynamically on an element.
But doing so raise a performance issue. Classes, stored as a single string, needed to be split for each selector. This split was slow due to both memory allocation and specific-case parsing of split_string.
To solve the issue, the classes are now kept into a vector table, created on set_attr. For compatibility issue, the class string is still stored as is in the attribute table

Optimize class handling

---

src/element.cpp
src/element.h
src/html_tag.cpp
src/html_tag.h

There are brilliant <code>select_one</code> methods in each html element for searching the tree. But they are useless when you want to list <em>all</em> the items for a CSS selector, not just the <em>first</em> one. So I've made <code>select_all()</code> methods for that. They return <code>elements_vector</code> and work recursively (just as <code>select_one</code>-s do).
Do you agree they are useful? I've tested them a bit already.

select_all() methods added to element and html_tag

---

src/element.cpp
src/element.h
src/html_tag.cpp
src/html_tag.h

I've added 2 methods: 
1. <code>removeChild</code> is symmetrical to <code>appendChild</code> - it removes the item from children and clears its parent.
2. <code>clearRecursive</code> removes all children (and disconnect their parents) from the element recursively.
Both methods are very useful for dynamic DOM manipulation.
In addition I would recommend to reconsider:
1. <code>children()</code> method that returns plain list - the modification of this list could lead to an inconsistent structure (for example if someone adds an item to it without setting parent of the item), so maybe it should be a constant method returning constant link? (all manipulations would be made with additional methods)
2. Maybe <code>elements_vector</code> should be changed from <code>std::vector</code> to …

Added removeChild and clearRecursive

---

src/el_image.cpp

I commented on the commit the crash fixed. It was caused by an image with dimensions 1x1 pixel.

fix scrolling issue with news.ycombinator.com on linux

---

CMakeLists.txt

On windows add gumbo as an include directory (to find strings.h)

---

CMakeLists.txt

Those options aren't known by Microsoft Visual Studio and cause trouble, because the default options get lost. A better way to set the C++ or C standard would be the property CXX_STANDARD and C_STANDARD, which are available from cmake 3.1 upwards.

Do not overwrite default compilation in msvc with unknown options!

---

CMakeLists.txt

While trying to build litehtml on my Mac I have noticed that the previous configurations did not apply the -std=c++11 by default which caused the build to fail
With this patch, it will at least always compile

CMAKE Use -std=c++11 for all configurations

---

CMakeLists.txt
cmake/litehtmlConfig.cmake
src/gumbo/CMakeLists.txt

Installing litehtml now installs the static library,
headers, and CMake configuration files.
So other projects can find and use litehtml with
find_package(litehtml)
when they add the litehtml installation path to CMAKE_PREFIX_PATH

Add install target and export for use with find_package

---

CMakeLists.txt

MinGW-w64 8.1.0 doesn't build on Windows by default, setting
LITEHTML_UTF8 makes the compile error go away.

CMake build: Add LITEHTML_UTF8 build option

---

src/os_types.h

void* causes linker errors with MinGW on Windows.

Use C++11's std::uint_ptr as litehtml::uint_ptr

---

src/html_tag.cpp

warning: '&&' within '||' [-Wlogical-op-parentheses]

Avoid compiler warning

---

include/litehtml/os_types.h

The WIN32 define is missing with MSVC 2019, use _WIN32

Fix build with MSVC 2019 and CMake

---

containers/haiku/container_haiku.cpp
containers/haiku/container_haiku.h

Partial implementation of a container for the Haiku Operating System using a BView as the rendering area. Supports default css, text and images so far, and rendering from a local file.
Example litebrowser at: https://github.com/adamfowleruk/litebrowser-haiku
Haiku at: https://www.haiku-os.org/

Feature haiku

---

CMakeLists.txt

Building litehtml on Linux using CMake failed with the following error:
```
[ 85%] Linking CXX executable litehtml_tests
liblitehtml.a(document.cpp.o): In function `void __gnu_cxx::new_allocator<litehtml::el_li>::construct<litehtml::el_li, std::shared_ptr<litehtml::document>&>(litehtml::el_li*, std::shared_ptr<litehtml::document>&)':
document.cpp:(.text._ZN9__gnu_cxx13new_allocatorIN8litehtml5el_liEE9constructIS2_JRSt10shared_ptrINS1_8documentEEEEEvPT_DpOT0_[_ZN9__gnu_cxx13new_allocatorIN8litehtml5el_liEE9constructIS2_JRSt10shared_ptrINS1_8documentEEEEEvPT_DpOT0_]+0x48): undefined reference to `litehtml::el_li::el_li(std::shared_ptr<litehtml::document> const&)'
collect2: error: ld returned 1 exit status
```
Adding src/el_li.cpp to the CMakeLists.txt file fixes this error and allows the …

Fix CMake build on Linux

---

include/litehtml/document.h
src/document.cpp

There's probably some better function extraction to be had between the functions I've added and litehtml::document::createFromUTF8, but I've gone with the minimal change for now.

Added support for loading HTML into an existing element

---

CMakeLists.txt
src/gumbo/CMakeLists.txt

CMake 3.19 starts warning:
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 2.8.12 will be removed from a future version of
CMake.
CMake 3.5 is already a very low minimum requirement.

Increase minimum CMake version to 3.5

---

src/num_cvt.cpp

Fixes failures like:
..\..\src\plugins\help\qlitehtml\litehtml\src\num_cvt.cpp(62):
error C2440: 'initializing': cannot convert from 'const char [2]' to
'litehtml::tchar_t *' ..\..\src\plugins\help\qlitehtml\litehtml\src\num_cvt.cpp(62):
note: Conversion from string literal loses const qualifier (see /Zc:strictStrings)

Build fix for MSVC 2019

---

CMakeLists.txt
src/gumbo/CMakeLists.txt

I'm packaging litehtml for Fedora, and I've added the following two patches to:
- Add a library version
- Honour LIB_SUFFIX

Patches from Fedora packaging

---

CMakeLists.txt

Patch currently carried downstream for Fedora packaging.

Add option to link against external gumbo

---

src/gumbo/char_ref.c
src/gumbo/char_ref.rl
src/gumbo/error.c
src/gumbo/include/gumbo/utf8.h
src/gumbo/parser.c
src/gumbo/tag.c
src/gumbo/tokenizer.c
src/gumbo/utf8.c
src/gumbo/vector.c

Fix warnings like
warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
with Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30037 for x64

gumbo: Fix MSVC warnings (64 bit)

---

CMakeLists.txt
src/document.cpp

Add a CMake option (USE_ICU) to enable the use of ICU to locate word
boundaries in strings.  If USE_ICU is enabled then split_text_node()
uses ICU's BreakIterator to split up a text node.  If USE_ICU is
disabled then split_text_node() uses the existing implementation to
split up a text node.
USE_ICU is disabled by default so this does not introduce a dependency
on ICU for existing litehtml users.

Add an option to use ICU to locate word boundaries

---

CMakeLists.txt
include/litehtml/os_types.h
include/litehtml/tstring_view.h
src/tstring_view.cpp
test/tstring_view_test.cpp

tstring_view is a string reference type that provides a view into a
string that is owned elsewhere (e.g., by a std::string object).
tstring_view implements the same interface as std::base_string_view in
the standard library.  When litehtml moves to C++17 consider replacing
the tstring_view implementation with the standard library
implementations (e.g., via a using statement).

Add tstring_view, a string reference type

---

CMakeLists.txt
src/document.cpp

Reverts litehtml/litehtml#161
One of the main purposes of litehtml is to be independent of any libraries and engines. Every external dependencies should be released via container methods.

Revert "Add an option to use ICU to locate word boundaries"

---

include/litehtml/html.h
include/litehtml/os_types.h
src/html.cpp

It has been implemented in the `html.cpp` file, inside the `litehtml` namespace.
This is not a complete `strtod` implementation:
- It ignores the exponent part.
- It does not set `errno`.
But it should be enough for the two uses of that function in `litehtml` source code.

Add a custom 'strtod' implementation that ignores the current locale.

---

include/litehtml/el_space.h
include/litehtml/element.h
src/box.cpp
src/el_space.cpp
src/element.cpp

'white-space:pre-wrap' allows to start new line with white-space if client width is configured not to fit trailing space at any line.
Tested with following html content:
```
<!DOCTYPE html>
<html>
<head>
<style>
div {
white-space: pre-wrap;
}
</style>
</head>
<body>
<div>
This is some text. This is some text. This is some text.
</div>
</body>
</html>
```
This can lead in the following output:
```
This is some text. This is some text.
This is some text.   <---   line starts with white-space!
```
Try yourself by shrinking browser window width to see the wrong line break and compare same content at e.g. w3schools.com

fixed style property 'white-space: pre-wrap'

---

src/el_li.cpp

Handles the start attribute in:
```html
<ol start=2>
<li>xyz</li>
</ol>
```

Handle start attribute in ordered lists

---

src/document.cpp

It should still update the document's media features, since those are used for rendering.

fix media_changed doing nothing when no media queries are present

---

CMakeLists.txt

EXTERNAL_GTEST option allows to use external GoogleTest instead of fetching it from GitHub.
It saves the maintainers of the litehtml package from creating patches for proper testing. Moreover, when gtest is fetched from GitHub, cmake --install installs gmock and gtest to system, which is very annoying considering I only install litehtml.

Add EXTERNAL_GTEST option in CMakeLists.txt

---

src/gumbo/include/gumbo.h
src/gumbo/include/gumbo/error.h
src/gumbo/include/gumbo/util.h

1. #define _CRT_SECURE_NO_WARNINGS is done unconditionally (but what if I've already done it?)
2. #define fileno _fileno is done unconditionally.. this actually is more related to compiling against the windows platform than using MSC. anyway a simple way to resolve it is to conditionalize it.

gumbo.h (and others) has two problems among them:

---

src/render_inline_context.cpp

text-indent currently skips the first line and indents subsequent lines. But it should be the other way around.

fixed text-indent

---

include/litehtml/master_css.h

This adds styles (underline) for the `<u>` element.
The styles for `<b>`/`<strong>` and `<i>`/`<em>` additionally have `display:inline;`. Should that be removed, or should it be added to the styles for `<u>` here?

Add styles for u element

---

CMakeLists.txt

since cmake does not have a built in way to specify testing options per-project this will allow tests for litehtml to be enabled or disabled explicitly when it is brought in as a dependency in a larger cmake project

add litehtml-specific testing option in cmake

---

src/media_query.cpp

According to https://www.w3.org/TR/mediaqueries-5/ section 3.2, Error Handling, an unknown media-type must be treated as not matching.

media_query: Treat unknown media type as none

---

CMakeLists.txt

Currently, tests only work when run from the `${litehtml_root}/build` directory. This commit makes it possible to build and run tests in an arbitrary directory. In particular, this avoids errors when building `litebrowser-linux` with the `-DLITEHTML_BUILD_TESTING:BOOL=ON` switch.

Add specifying a working directory for tests

---

containers/cairo/cairo_images_cache.h

Detailed error context: 
containers/cairo/cairo_images_cache.h:64:11: note: in instantiation of template class 'std::__value_type<std::string, cairo_surface_wrapper>' requested here
if(iter != m_images.end())
MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/__utility/pair.h:54:5: error: the parameter for this explicitly-defaulted copy constructor is const, but a member or base requires it to be non-const
pair(pair const&) = default;

Fix build error caused by non-const copy ctor of cairo_surface_wrapper

---

src/style.cpp

Example of the supported syntax:
```
property: var(--variable, def_value)
```
Also nested vars are supported
```
property: var(--variable, var(--variable-two, def_value))
```

Support for default value of the var() function.

---

CMakeLists.txt

This makes the headers show up in IDEs as well as the source files.

{cmake} Add includes to add_library()

---

include/litehtml/html_microsyntaxes.h
src/css_selector.cpp
src/html_microsyntaxes.cpp

Also use .empty() instead of equality.

These strings are not modified, so pass by ref

---

containers/haiku/container_haiku.cpp

Debug values of border widths were incorrect on output.
(I'm not building haiku - just noticed it when reading the code.)

{haiku} Fix debug output in LiteHtmlView::draw_borders()

---

src/encodings.cpp

https://releases.llvm.org/17.0.1/tools/clang/tools/extra/docs/clang-tidy/checks/bugprone/macro-parentheses.html

Use parens in macro

---

src/css_selector.cpp
src/document.cpp
src/encodings.cpp
src/html_tag.cpp
src/style.cpp

https://releases.llvm.org/17.0.1/tools/clang/tools/extra/docs/clang-tidy/checks/readability/container-size-empty.html
(Also sneak in removal of a redundant initialization.)
Part of #336

{style} Prefer .empty() for readability

---

CMakeLists.txt
containers/cairo/container_cairo_pango.cpp
containers/cairo/render2png.cpp
include/litehtml/document.h
include/litehtml/master_css.h
include/litehtml/render_item.h
include/litehtml/types.h
src/css_properties.cpp
src/document.cpp
src/html_tag.cpp
src/media_query.cpp
src/render_block.cpp
src/render_image.cpp
src/render_item.cpp
src/render_table.cpp
src/style.cpp

Changes:
1. Added support for 'ex' and 'ch' units.
2. Improved calculating of the x-height metric.
3. Use border box to check intersection with the clip in the draw_background
4. Pango container: fixed font height calculation and draw
5. Improvements in positioning of elements with position absolute and fixed
6. Total 5595 tests are passed

Update to pass tests

---

include/litehtml/css_properties.h
include/litehtml/string_id.h
include/litehtml/types.h
src/css_properties.cpp
src/style.cpp

Because litehtml itself does not implement input widgets, this is simply a passthrough value to allow applications implementing input support to handle the property.
References:
- https://www.w3.org/TR/css-ui-4/#appearance-switching
- https://developer.mozilla.org/en-US/docs/Web/CSS/appearance
MDN references some non-standard values, as well as the `-webkit-appearance` and `-moz-appearance` vendor prefixes (the `-webkit` prefix is common enough that the W3 spec references it as well), but for this PR I opted to just handle the values directly referenced in the standard.
Please let me know if anything else is needed to get this merged!

Add support for the "appearance" CSS property

---

src/gumbo/CMakeLists.txt

CMake Deprecation Warning at src/gumbo/CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 3.10 will be removed from a future version of
CMake.
Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
to tell CMake that the project requires at least <min> but has been updated
to work with policies introduced by <max> or earlier.

cmake fix warning in gumbo

---

CMakeLists.txt
containers/cairo/container_cairo_pango.cpp
containers/cairo/container_cairo_pango.h
include/litehtml/css_properties.h
include/litehtml/document.h
include/litehtml/document_container.h
include/litehtml/font_description.h
include/litehtml/string_id.h
include/litehtml/style.h
include/litehtml/types.h
src/css_properties.cpp
src/document.cpp
src/style.cpp

Supported properties:
* text-decoration (as shorthand for other text-decoration properties)
* text-decoration-color
* text-decoration-line
* text-decoration-style
* text-decoration-thickness
Changes in the container::create_font:
```litehtml::uint_ptr create_font(const font_description& descr, const document* doc, litehtml::font_metrics* fm);```
All font parameters are moved to the ```font_description``` structure.

Support for text-decoration CSS properties

---

CMakeLists.txt
include/litehtml/element.h
include/litehtml/render_item.h
src/render_item.cpp

Fixes:
1. Incorrect text position in floating elements with negative ```margin-left```.
2. Disable top/bottom margins collapse for elements with ```position:fixed```

Some small fixes
